s = set()
num1 = int(input("Enter first number: "))
s.add(num1)
num2 = int(input("Enter second number: "))
s.add(num2)
num3 = int(input("Enter third number: "))
s.add(num3)
num4 = int(input("Enter fourth number: "))
s.add(num4)
num5 = int(input("Enter fifth number: "))
s.add(num5)
num6 = int(input("Enter sixth number: "))
s.add(num6)
num7 = int(input("Enter seventh number: "))
s.add(num7)
num8 = int(input("Enter eighth number: "))
s.add(num8)

print(s)