d = {}
name = input("Enter your name: ")
lan = input("Enter your favourite language: ")
d.update({name: lan})
name = input("Enter your name: ")
lan = input("Enter your favourite language: ")
d.update({name: lan})
name = input("Enter your name: ")
lan = input("Enter your favourite language: ")
d.update({name: lan})
name = input("Enter your name: ")
lan = input("Enter your favourite language: ")
d.update({name: lan})
print(d)